### ISSUE TITLE
Convert line paths to curves

### ISSUE THREAD

**Issue by thisisaaronland** [aaronland/fingerprint#4]
Initial tests to smooth the strokes captured by `raphael-sketchpad` at runtime proved to be very slow and were abandoned.

* https://github.com/Jam3/chaikin-smooth/blob/master/index.js
* https://github.com/aaronland/fingerprint/blob/main/www/javascript/raphael.sketchpad.js#L725-L746

See also: 

* https://francoisromain.medium.com/smooth-a-svg-path-with-cubic-bezier-curves-e37b49d46c74
* https://medium.com/@bragg/cubic-bezier-curves-with-svg-paths-a326bb09616f

**Comment by straup** [comment]
* https://github.com/jimnewpower/line-smoothing
* https://medium.com/phcacique/chaikins-algorithm-for-drawing-curves-7d19b2e0e209

**Comment by straup** [comment]
Investigate https://github.com/steveruizok/perfect-freehand

**Comment by thisisaaronland** [comment]
Investigate: https://github.com/ajstarks/giocanvas/tree/master/bezsketch

**Comment by straup** [comment]
* https://www.sitepoint.com/html5-svg-quadratic-curves/
* https://www.sitepoint.com/html5-svg-cubic-curves/
* https://svg-path-visualizer.netlify.app/bezier-curve/
* https://www.summbit.com/blog/bezier-curve-guide/

**Comment by straup** [comment]
* https://github.com/volkerp/fitCurves

**Comment by straup** [comment]
* http://mourner.github.io/simplify-js/

**Comment by thisisaaronland** [comment]
* https://www.nan.fyi/svg-paths

**Comment by straup** [comment]
* https://icons.getbootstrap.com/icons/bezier2/
